### ISSUE TITLE
재문의/답변 API 구현방식

### ISSUE THREAD

**Issue by BbingDdang** [kookmin-sw/capstone-2023-45#29]
재문의/답변 api 관련 inqury id 통일에 대한 논의.

- parent id를 받아 inqury id로 사용 가능하지 혹은 다른 방법이 있을지.

**Comment by okps123** [comment]
PR에도 코멘트 했지만 Github PR처럼 문의 하나에 여러 답변이 오고갈 수 있는 구조면 좋을 것 같아요.
게시글과 댓글처럼 Inquery -> InqueryComment로 구분해보면 어떨까요?
